<?php
/**
 * Copyright © Klarna Bank AB (publ)
 *
 * For the full copyright and license information, please view the NOTICE
 * and LICENSE files that were distributed with this source code.
 */

/** @var Klarna\Onsitemessaging\Block\Cart $block */
/** @var Magento\Framework\Escaper $escaper */

if ($block->showInCart()):
    ?>
    <div id="klarna-osm-placement-cart"></div>

    <script async>
        window.addEventListener('klarna-sdk-ready', function (event) {
            const PluginKlarnaWebSdk = event.detail.sdk;

            PluginKlarnaWebSdk.Messaging.placement({
                key: "<?= $escaper->escapeHtml($block->getKey()) ?>",

                <?php if ($block->getTheme()): ?>
                theme: "<?= $escaper->escapeHtml($block->getTheme()) ?>",
                <?php endif ?>

                <?php if ($block->getPurchaseAmount()): ?>
                purchaseAmount: "<?= $escaper->escapeHtml($block->getPurchaseAmount()) ?>",
                <?php endif ?>

                locale: "<?= $escaper->escapeHtml($block->getLocale()) ?>"
            }).mount('#klarna-osm-placement-cart');
        });
    </script>

    <script type="text/x-magento-init">
    {
        "*": {
            "Klarna_Onsitemessaging/js/cart-update": true
        }
    }
    </script>
<?php endif ?>
